INSERT INTO USER ("FIRST_NAME","LAST_NAME","PASSWORD","USER_NAME") VALUES('Wilkins','Liang','100200','wilkins') 



INSERT INTO PHOTO ("DESCRIPTION","IMAGE_NAME","LIKES","PHOTO_NAME","TITLE","USER_USER_ID")VALUES('SAMPLE PHOTO','SAMPLE1','0','SAMPLE','SAMPLE TITLE','1')
INSERT INTO PHOTO ("DESCRIPTION","IMAGE_NAME","LIKES","PHOTO_NAME","TITLE","USER_USER_ID")VALUES('SAMPLE PHOTO2','SAMPLE2','0','SAMPLE2','SAMPLE2 TITLE','1')
